# -*- coding: utf-8 -*-
"""data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vvMjXdNBdDGKOzPu_y85J1UMe-K-xyWR
"""

import csv, os
import pandas as pd

file_path = '/content/Cities.csv'

cities = []
with open(file_path) as f:
    rows = csv.DictReader(f)
    for r in rows:
        cities.append(dict(r))

for city in cities[:5]:
    print(city)

print("\nThe average temperature of all the cities (manual loop):")
temps = []
for city in cities:
    temps.append(float(city['temperature']))
print(sum(temps) / len(temps))

print("\nThe average temperature of all the cities (list comprehension):")
temps = [float(city['temperature']) for city in cities]
print(sum(temps) / len(temps))
print()

df = pd.read_csv(file_path)
df.columns = [c.strip().lower() for c in df.columns]

print("\nCities in Germany:")
cities_in_germany = df[df['country'].str.strip().str.lower() == 'germany']
print(cities_in_germany)

print("\nCities in Spain with temperature > 12°C:")
spain_above_12 = df[
    (df['country'].str.strip().str.lower() == 'spain') &
    (df['temperature'] > 12)
]
print(spain_above_12)

unique_countries = df['country'].nunique()
print("\nNumber of unique countries:", unique_countries)

avg_temp_germany = df.loc[
    df['country'].str.strip().str.lower() == 'germany', 'temperature'
].mean()
print("Average temperature for cities in Germany:", avg_temp_germany)

max_temp_italy = df.loc[
    df['country'].str.strip().str.lower() == 'italy', 'temperature'
].max()
print("Max temperature for cities in Italy:", max_temp_italy)